Repository mitalrs/Short-Profile-With-HTML-CSS, pull requests merged in 2022-10, with the labels that each got.

#11 Raunak-profile Added with Readme.md
  CONTRIBUTING.md
  Raunak/README.md
  Raunak/Raunak.css
  Raunak/Raunak.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 Profile Added by Pratap360
  CONTRIBUTING.md
  Pratap360/Readme.md
  Pratap360/img/github profile img.jfif
  Pratap360/img/ss of profile.jpg
  Pratap360/index.html
  Pratap360/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#22 Added short profile and updated CONTRIBUTING.md
  Atul/README.md
  Atul/atul.css
  Atul/atul.html
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#23 hacktoberfest2022
  CONTRIBUTING.md
  raj-hero/README.md
  raj-hero/android-chrome-192x192.png
  raj-hero/index.html
  raj-hero/particles.json
  raj-hero/raj-hro-prf-ss.png
  raj-hero/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#29 Added My Profile Card
  satwik/readme.md
  satwik/satwik.css
  satwik/satwik.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 updated repository to solve conflicts
  CONTRIBUTING.md
  Piyush/README.md
  Piyush/images/IMG_20220506_021038_424.jpg
  Piyush/images/Screenshot at 2022-10-07 21-56-57.png
  Piyush/piyush.css
  Piyush/piyush.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#41 Aaditya Mishra profile card
  .vscode/settings.json
  Aaditya-Mishra/README.md
  Aaditya-Mishra/Vector.png
  Aaditya-Mishra/index.html
  Aaditya-Mishra/profile image.png
  Aaditya-Mishra/style.css
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, required-changes

#43 Add Fabian profile design
  CONTRIBUTING.md
  FabianCristancho/README.md
  FabianCristancho/images/bg-pattern-bottom.svg
  FabianCristancho/images/bg-pattern-card.svg
  FabianCristancho/images/bg-pattern-top.svg
  FabianCristancho/images/design.png
  FabianCristancho/images/fabian.jpg
  FabianCristancho/images/icon.png
  FabianCristancho/index.html
  FabianCristancho/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, required-changes

#60 Added my potfolio card
  .idea/.gitignore
  .idea/Short-Profile-With-HTML-CSS.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  CONTRIBUTING.md
  Shreeyash Garde/css/styles.css
  Shreeyash Garde/images/Shreeyash photo-modified2.png
  Shreeyash Garde/images/preview.png
  Shreeyash Garde/index.html
  Shreeyash Garde/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#56 vermilion4 profile added
  Adaeze/Adaeze_Resume.pdf
  Adaeze/README.md
  Adaeze/images/Readme-screenshot.png
  Adaeze/images/ada.jpg
  Adaeze/index.html
  Adaeze/styles.css
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#58 Add files via upload
  Swadesh/Profile.png
  Swadesh/index.html
  Swadesh/my photo.jpg
  Swadesh/readme.md
  Swadesh/style.css
Labels: required-changes

#49 Harsha bajaj-profile card
  Harsha-Bajaj/img.jpeg
  Harsha-Bajaj/index.html
  Harsha-Bajaj/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#46 Added profile card
  Shital/Img/Facebook.PNG
  Shital/Img/Github.PNG
  Shital/Img/Instagram.PNG
  Shital/Img/Twitter.PNG
  Shital/Img/profilephoto.jpg
  Shital/Readme.md
  Shital/index.html
  Shital/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#39 added profile card
  Lokesh/README.md
  Lokesh/lokesh.css
  Lokesh/lokesh.html
Labels: hacktoberfest, required-changes

#32 Sujit
  Sujit is Back/Panda_Archigraphs.png
  Sujit is Back/Readme.md
  Sujit is Back/index.css
  Sujit is Back/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#30 Naman
  naman/README.md
  naman/assests/card.png
  naman/assests/hater_fr.png
  naman/assests/instagram.png
  naman/assests/linkedin.png
  naman/assests/profile.png
  naman/assests/twitter.png
  naman/index.html
  naman/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Index profile page added
  CONTRIBUTING.md
  Rahul Sehgal/images/github.jpg
  Rahul Sehgal/images/instagram.jpg
  Rahul Sehgal/images/linkedin.jpg
  Rahul Sehgal/images/profile_image_crowninn.jpg
  Rahul Sehgal/rahul.html
  Rahul Sehgal/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Abhishek
  Abhishek/Abhishek.css
  Abhishek/Abhishek.html
  Abhishek/CONTRIBUTING.md
  Abhishek/IMAGE.png
  Abhishek/Readme.md
  Abhishek/joker-artwork-5k.jpg
  Abhishek/wp2655933.jpg
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
